src/Entity/Lieu.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LieuRepository")
 */
class Lieu
{
    use MediaContainerTrait;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type;

    /**
     * @ORM\Column(type="text")
     */
    private $presentation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $num_telephone;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_createur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $user_contact;

    /**
     * @var ?\Doctrine\Common\Collections\ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Media", cascade={"all"}, mappedBy="lieu")
     */
    private $medias;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"all"}, orphanRemoval=true)
     * @var ?\App\Entity\Image
     */
    private $image;

    /**
     * @var bool
     */
    private $deleteImage;

    public function __construct()
    {
        $this->deleteImage = false;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getNumTelephone(): ?string
    {
        return $this->num_telephone;
    }

    public function setNumTelephone(?string $num_telephone): self
    {
        $this->num_telephone = $num_telephone;

        return $this;
    }

    public function getUserCreateur(): ?User
    {
        return $this->user_createur;
    }

    public function setUserCreateur(?User $user_createur): self
    {
        $this->user_createur = $user_createur;

        return $this;
    }

    public function getUserContact(): ?User
    {
        return $this->user_contact;
    }

    public function setUserContact(?User $user_contact): self
    {
        $this->user_contact = $user_contact;

        return $this;
    }

    /**
     * Get the value of medias
     *
     * @return  ?\Doctrine\Common\Collections\ArrayCollection
     */ 
    public function getMedias()
    {
        return $this->medias;
    }

    /**
     * Set the value of medias
     *
     * @param  ?\Doctrine\Common\Collections\ArrayCollection  $medias
     *
     * @return  self
     */ 
    public function setMedias(?\Doctrine\Common\Collections\ArrayCollection $medias)
    {
        $this->medias = $medias;

        return $this;
    }

    /**
     * Set one value of medias
     */
    public function addMedia($media)
    {
        $this->medias[] = $media;

        return $this;
    }

    /**
     * Get the value of image
     *
     * @return  ?\App\Entity\Image
     */ 
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set the value of image
     *
     * @param  ?\App\Entity\Image  $image
     *
     * @return  self
     */ 
    public function setImage(?\App\Entity\Image $image)
    {
        if ($image instanceof Image && !is_null($image->getFile())){ // Test si une image est envoyéee
            $this->image = $image;
        }

        return $this;
    }

    /**
     * Get the value of deleteImage
     *
     * @return  bool
     */ 
    public function getDeleteImage()
    {
        return $this->deleteImage;
    }

    /**
     * Set the value of deleteImage
     *
     * @param  bool  $deleteImage
     *
     * @return  self
     */ 
    public function setDeleteImage(bool $deleteImage)
    {
        $this->deleteImage = $deleteImage;
        if ($deleteImage){
            $this->image = null;
        }

        return $this;
    }
}

src/Form/LieuType.php
<?php

namespace App\Form;

use App\Entity\Lieu;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

use App\Form\ImageType;


class LieuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('photoIdent', MediaType::class, array(
            //     'label' => 'lieu.photo',
            //     'mapped' => false,
            // ))

            ->add('image', ImageType::class, array(
                'label' => 'lieu.photo',
            ))

            ->add('nom', Type\TextType::class, array(
                'label' => 'lieu.nom',
                'required' => true,
            ))

            ->add('type', ChoiceButtonType::class, array(
                'label' => 'lieu.type',
                'choices' => array(
                    'Bar' => 'Bar',
                    'Maison de la Jeunesse et de la Culture' => 'MJC',
                    'Plein air' => 'Plein air',
                    'Salle des fêtes' => 'Salle des fêtes',
                    'Salle de concert' => 'Salle de concert',
                ),
                'required' => true,
                'expanded' => true,
            ))

            ->add('presentation', Type\TextareaType::class, array(
                'label' => 'lieu.presentation',
                'required' => true,
            ))

            ->add('adresse', Type\TextType::class, array(
                'label' => 'lieu.adresse',
                'required' => true,
            ))
            
            ->add('code_postal', Type\IntegerType::class, array(
                'label' => 'lieu.code_postal',
                'required' => true,
            ))
            
            ->add('ville', Type\TextType::class, array(
                'label' => 'lieu.ville',
                'required' => true,
            ))
            /*
            ->add('latitude', Type\NumberType::class, array(
                'label' => 'lieu.latitude',
                'required' => false,
                'scale' => 5
            ))
            
            ->add('longitude', Type\NumberType::class, array(
                'label' => 'lieu.longitude',
                'required' => false,
                'scale' => 5
            ))
            */
            ->add('num_telephone', Type\TelType::class, array(
                'label' => 'lieu.num_telephone',
                'required' => false,
            ))
        ;

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $event){
            $entity = $event->getData(); // Entité envoyée au formulaire
            $form = $event->getForm(); // Récupère le formulaire

            if (!is_null($entity->getImage())) { // S'il y a une image dans mon lieu
                // Ajout du champ "deleteImage" seulement s'il y a une image
                $form->add('deleteImage', Type\CheckboxType::class, array(
                    'label' => 'image.delete',
                    'required' => false, // Désactive le required
                ));
            }

        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Lieu::class,
        ]);
    }
}

src/Controller/Admin/LieuController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use App\Entity\Lieu;
use App\Form\LieuType;

/**
 * @Route("/admin/lieu", name="admin_lieu_")
 */
class LieuController extends Controller
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $entities = $em->getRepository(Lieu::class)->findAll();

        return $this->render('admin/lieu/index.html.twig', [
            'entities' => $entities,
        ]);
    }

    /**
     * @Route("/new", name="new")
     */
    public function new(Request $request)
    {
        $entity = new Lieu;
        $form = $this->createForm(LieuType::class, $entity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            $t = $this->get('translator');
            $this->addFlash('success', $t->trans('lieu.new.success'));

            return $this->redirectToRoute('admin_lieu_index');
        }

        return $this->render('admin/lieu/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function edit(Request $request, Lieu $entity)
    {
        $form = $this->createForm(LieuType::class, $entity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            $t = $this->get('translator');
            $this->addFlash('success', $t->trans('lieu.edit.success'));

            return $this->redirectToRoute('admin_lieu_index');
        }

        return $this->render('admin/lieu/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete", requirements={"id" = "\d+"})
     */
    public function delete(Request $request, Lieu $entity)
    {
        $form = $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_lieu_delete', ['id' => $entity->getId()])) // action=""
            ->setMethod('DELETE')
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->remove($entity);
            $em->flush();

            // Crée un message de confirmation
            $t = $this->get('translator');
            $this->addFlash('success', $t->trans('lieu.delete.success'));

            return $this->redirectToRoute('admin_lieu_index');
        }

        return $this->render('admin/lieu/delete.html.twig', array(
            'form' => $form->createView(), // Envoi le formulaire à la vue
            'entity' => $entity,
        ));
    }
}

src/Controller/LieuController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route; // Définir les routes en annotations
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\GenericEvent;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Translation\TranslatorInterface;

use App\Form\LieuType;
use App\Entity\Lieu;

/**
 * @Route("/lieu", name="lieu_")
 */
class LieuController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $entities = $em->getRepository(Lieu::class)->findAll();

        return $this->render('lieu/index.html.twig', [
            'entities' => $entities,
            'newEntity' => new Lieu, // Pour tester avec le voter
        ]);
    }

    /**
     * @Route("/show/{id}", name="show")
     */
    public function show($id)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository(Lieu::class)->findOneById($id);
        
        return $this->render('/lieu/show.html.twig', array(
            'entity' => $entity,
            'mediaWithPhotoIdent' => $entity->getMediaWithPhotoIdent(),
        ));
    }

    /**
     * @Route("/new", name="new")
     */
    public function new(Request $request, EventDispatcherInterface $eventDispatcher, TranslatorInterface $translator)
    {
        // Affiche un deny Access si l'utilisateur ne peut pas modifier
        // $this->denyAccessUnlessGranted('create', $lieu);

        $entity = new Lieu;
        $entity->setUserCreateur($this->getUser());
        $form = $this->createForm(LieuType::class, $entity);
        $form->handleRequest($request); // Envoi les données de requêtes (POST) au formulaire

        if ($form->isSubmitted() && $form->isValid()) { // Si le form est envoyé et valide

            // Ajout du nouvel lieu dans la db
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity); // Prépare la requête
            $em->flush(); // Execute la requête

            // Crée un message de confirmation
            $this->addFlash('success', $translator->trans('lieu.new.success'));

            // Déclanchement de l'événement 'lieu.add'
            $event = new GenericEvent($entity);
            $eventDispatcher->dispatch('lieu.add', $event);

            return $this->redirectToRoute('lieu_index'); // Retour sur la liste des lieux
        }

        return $this->render('lieu/new.html.twig', array(
            'form' => $form->createView(), // Envoi le formulaire à la vue
        ));
    }

    /**
     * @Route("/edit/{id}", name="edit", requirements={"id" = "\d+"})
     */
    public function edit(Request $request, Lieu $entity, TranslatorInterface $translator)
    {
        // Affiche un deny Access si l'utilisateur ne peut pas modifier
        $this->denyAccessUnlessGranted('edit', $entity);
        // $this->isGranted('edit', $lieu);

        $form = $this->createForm(LieuType::class, $entity);
        $form->handleRequest($request); // Envoi les données de requêtes (POST) au formulaire

        if ($form->isSubmitted() && $form->isValid()) { // Si le form est envoyé et valide
            // Ajout du nouvel lieu dans la db
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity); // Prépare la requête
            $em->flush(); // Execute la requête

            // Crée un message de confirmation
            $this->addFlash('success', $translator->trans('lieu.edit.success'));

            return $this->redirectToRoute('lieu_index'); // Retour sur la liste des lieux
        }

        return $this->render('lieu/edit.html.twig', array(
            'form' => $form->createView(), // Envoi le formulaire à la vue
            'entity' => $entity,
        ));
    }

    /**
     * @Route("/delete/{id}", name="delete", requirements={"id" = "\d+"})
     */
    public function delete(Request $request, Lieu $lieu): Response
    {
        // Affiche un deny Access si l'utilisateur ne peut pas modifier
        $this->denyAccessUnlessGranted('edit', $lieu);

        if ($this->isCsrfTokenValid('delete'.$lieu->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($lieu);
            $em->flush();
        }

        return $this->redirectToRoute('lieu_index');
    }
}

templates/lieu/_delete_form.html.twig
{# C'est visible seulement si l'user connecté est l'usercreateur sont pareils #}
<button type="button" class="btn btn-lieu text-light" data-toggle="modal" data-target="#deleteModal">
  Supprimer
</button>

<form method="post" action="{{ path('lieu_delete', {'id': entity.id }) }}">
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="deleteModalLabel">Supression d'un lieu</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Etes-vous sûr de vouloir supprimer ce lieu ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Annuler</button>
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ entity.id) }}">
        <button class="btn btn-lieu text-light">Supprimer</button>
      </div>
    </div>
  </div>
</div>
</form>

templates/lieu/_form.html.twig
  
  <div class="row">
    <div class="col-md-8">
        {{ form_row(form.image) }}
    </div>
    <div class="col-md-4 col-lg-2">
      {% if entity is defined and entity.image is not empty %}
        <img class="w-100" src="{{ asset('/uploads/img/' ~ entity.image.path) }}" alt="{{ entity.nom }}" />
        {{ form_row(form.deleteImage) }}
      {% endif %}
    </div>
  </div>

  {{ form_widget(form) }}

templates/lieu/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Modifier {{ entity.nom}} | P'tites Scènes{% endblock %}

{% block page_content %}
    <div class="lieu row justify-content-center">
        <div class="col-10 mt-3 px-0 pb-5">
            {{ form_start(form) }}
                {% embed 'decorator/_card.html.twig' %}
                    {% block header %}
                        <h1>Modification d'un lieu</h1>
                    {% endblock %}
        
                    {% block body %}
                        {{ include('lieu/_form.html.twig', {'button_label': 'Modifier'}) }}
                    {% endblock %}
        
                    {% block footer %}
                        <a class="btn btn-dark" href="{{ path('lieu_show', {'id': entity.id }) }}">Annuler</a>
                        <button class="btn btn-lieu text-light">{{ button_label|default('Enregistrer') }}</button>
                    {% endblock %}
                {% endembed %}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/lieu/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Lieux | P'tites Scènes{% endblock %}

{% block page_content %}

<div class="lieu row justify-content-center">
    <div class="col-10 px-0 mt-3 pb-5">
        {% for entity in entities %}
            <a href="{{ path('lieu_show', {'id': entity.id}) }}">                
                {% if is_granted('edit', entity) %}
                    <div class="card-group mb-3 border-createur-lieu">
                {% else %}
                    <div class="card-group mb-3 border-standard ">
                {% endif %}
                <div class="card col-2 bg-dark px-0">
                        {% if entity.getMediaWithPhotoIdent() is not empty %}
                            <img class="card-img-top" src="{{ asset('/uploads/img/' ~ entity.getMediaWithPhotoIdent().lien) }}" alt="{{ entity.getMediaWithPhotoIdent().titre }}">
                        {% elseif entity.image is not empty %}
                            <img class="card-img-top" src="{{ asset('/uploads/img/' ~ entity.image.path) }}" alt="{{ entity.nom }}">
                        {% else %}
                            <img class="card-img-top" src="{{ asset('/img/lieu_def.jpg') }}" alt="Card image cap">
                        {% endif %}
                    </div>
                    <div class="card col-7 bg-dark text-light p-2">
                        <h4 class="text_lieu">{{ entity.nom }}</h4>
                        <p><small>{{ entity.type }}</small></p>
                        <p>{{ entity.presentation }}</p>
                    </div>
                    <div class="card col-3 bg-dark text-light p-3">
                        <p class="subtitle">{{ entity.adresse }}</p>
                        <p class="subtitle">{{ entity.codePostal }} - {{ entity.ville }}</p>
                        <p class="subtitle">{{ entity.numTelephone }}</p>
                    </div>
                </div>
            </a>                    
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/lieu/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Créer un lieu | P'tites Scènes{% endblock %}

{% block page_content %}
    <div class="lieu row justify-content-center">
        <div class="col-10 mt-3 px-0 pb-5">
            {{ form_start(form) }}
                {% embed 'decorator/_card.html.twig' %}
                    {% block header %}
                        <h1> {{ 'lieu.new.title'|trans }} </h1>
                    {% endblock %}
        
                    {% block body %}
                        {{ include('lieu/_form.html.twig', {'button_label': 'Créer'}) }}
                    {% endblock %}
        
                    {% block footer %}
                        <a class="btn btn-dark" href="{{ path('lieu_index') }}">Annuler</a>
                        <button class="btn btn-lieu text-light">{{ button_label|default('Enregistrer') }}</button>
                    {% endblock %}
                {% endembed %}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/lieu/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ entity.nom }} | P'tites Scènes{% endblock %}

{% block page_content %}

<div class="lieu row justify-content-center">
    <div class="col-10 mt-3 px-0 pb-5">
        <div class="card">
            <div class="card-body p-0">
                <div class="card-group">
                    <div class="card col-5 bg-dark px-0 border-0">
                        {% if entity.getMediaWithPhotoIdent() is not empty %}
                            <img class="card-img-top" src="{{ asset('/uploads/img/' ~ entity.getMediaWithPhotoIdent().lien) }}" alt="{{ entity.getMediaWithPhotoIdent().titre }}">
                        {% elseif entity.image is not empty %}
                            <img class="card-img-top" src="{{ asset('/uploads/img/' ~ entity.image.path) }}" alt="{{ entity.nom }}">
                        {% else %}
                            <img class="card-img-top" src="{{ asset('/img/lieu_def.jpg') }}" alt="Card image cap">
                        {% endif %}
                    </div>
                    <div class="card col-7 bg-dark text-light text-center p-3">
                        <h2 class="card-title text_lieu">
                            {{ entity.nom }}
                        </h2>
                        <p class="small mt-3">{{ entity.type }}</p>
                        <hr>
                        {% if entity.presentation is not empty %}
                                <p class="card-text text-light text-left mt-3"> {{ entity.presentation }} </p>
                        {% endif %}
                    </div>
                    <hr>
                    <ul class="list-group list-group-flush bg-dark">
                        <li class="list-group-item bg-dark text-light">{{ entity.adresse }}</li>
                        <li class="list-group-item bg-dark text-light">{{ entity.CodePostal() }}</li>
                        <li class="list-group-item bg-dark text-light">{{ entity.ville }}</li>
                        <li class="list-group-item bg-dark text-light">{{ entity.NumTelephone() }}</li>
                    </ul>
                </div>
            </div>
            <div class="card-footer text-right bg-light">
                <div class="btn-group">
                    <a href="{{ path('lieu_index') }}" class="btn btn-lieu text-light">Retour</a>
                    {% if is_granted('edit', entity) %}
                        <a href="{{ path('lieu_edit', {'id': entity.id }) }}" class="btn btn-dark">Modifier</a>
                        {{ include('lieu/_delete_form.html.twig') }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}