src/Entity/Lieu.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LieuRepository")
 */
class Lieu
{
    use MediaContainerTrait;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type;

    /**
     * @ORM\Column(type="text")
     */
    private $presentation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $num_telephone;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_createur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $user_contact;

    /**
     * @var ?\Doctrine\Common\Collections\ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Media", cascade={"all"}, mappedBy="lieu")
     */
    private $medias;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"all"}, orphanRemoval=true)
     * @var ?\App\Entity\Image
     */
    private $image;

    /**
     * @var bool
     */
    private $deleteImage;

    public function __construct()
    {
        $this->deleteImage = false;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getNumTelephone(): ?string
    {
        return $this->num_telephone;
    }

    public function setNumTelephone(?string $num_telephone): self
    {
        $this->num_telephone = $num_telephone;

        return $this;
    }

    public function getUserCreateur(): ?User
    {
        return $this->user_createur;
    }

    public function setUserCreateur(?User $user_createur): self
    {
        $this->user_createur = $user_createur;

        return $this;
    }

    public function getUserContact(): ?User
    {
        return $this->user_contact;
    }

    public function setUserContact(?User $user_contact): self
    {
        $this->user_contact = $user_contact;

        return $this;
    }

    /**
     * Get the value of medias
     *
     * @return  ?\Doctrine\Common\Collections\ArrayCollection
     */ 
    public function getMedias()
    {
        return $this->medias;
    }

    /**
     * Set the value of medias
     *
     * @param  ?\Doctrine\Common\Collections\ArrayCollection  $medias
     *
     * @return  self
     */ 
    public function setMedias(?\Doctrine\Common\Collections\ArrayCollection $medias)
    {
        $this->medias = $medias;

        return $this;
    }

    /**
     * Set one value of medias
     */
    public function addMedia($media)
    {
        $this->medias[] = $media;

        return $this;
    }

    /**
     * Get the value of image
     *
     * @return  ?\App\Entity\Image
     */ 
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set the value of image
     *
     * @param  ?\App\Entity\Image  $image
     *
     * @return  self
     */ 
    public function setImage(?\App\Entity\Image $image)
    {
        if ($image instanceof Image && !is_null($image->getFile())){ // Test si une image est envoyéee
            $this->image = $image;
        }

        return $this;
    }

    /**
     * Get the value of deleteImage
     *
     * @return  bool
     */ 
    public function getDeleteImage()
    {
        return $this->deleteImage;
    }

    /**
     * Set the value of deleteImage
     *
     * @param  bool  $deleteImage
     *
     * @return  self
     */ 
    public function setDeleteImage(bool $deleteImage)
    {
        $this->deleteImage = $deleteImage;
        if ($deleteImage){
            $this->image = null;
        }

        return $this;
    }
}

src/Controller/Admin/EvenementController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use FOS\UserBundle\Model\UserManagerInterface;

/**
 * @Route("/admin/evenement")
 */
class EvenementController extends AbstractController
{
    /**
     * @Route("/", name="admin_evenement_index", methods="GET")
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('admin/evenement/index.html.twig', ['evenements' => $evenementRepository->findAll()]);
    }

    /**
     * @Route("/new", name="admin_evenement_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $evenement = new Evenement;

        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em  = $this->getDoctrine()->getManager();
            $em->persist($evenement); //Prépare la requête 
            $em->flush();

            return $this->redirectToRoute('admin_evenement_index');
        }

        return $this->render('admin/evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_evenement_show", methods="GET")
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('admin/evenement/show.html.twig', ['evenement' => $evenement]);
    }

    /**
     * @Route("/{id}/edit", name="admin_evenement_edit", methods="GET|POST")
     */
    public function edit(Request $request, Evenement $evenement): Response
    {
        //$evenementManager = $this->get('fos_evenement.evenement_manager');
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em  = $this->getDoctrine()->getManager();
            $em->persist($entity); //Prépare la requête 
            $em->flush();

            return $this->redirectToRoute('admin_evenement_index', ['id' => $evenement->getId()]);
        }

        return $this->render('admin/evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_evenement_delete", methods="DELETE")
     */
    public function delete(Request $request, Evenement $evenement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($evenement);
            $em->flush();
        }

        return $this->redirectToRoute('admin_evenement_index');
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route; // Définir les routes en annotations
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\GenericEvent;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Translation\TranslatorInterface;

use App\Form\EvenementType;
use App\Entity\Evenement;

/**
 * @Route("/evenement", name="evenement_")
 */
class EvenementController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $entities = $em->getRepository(Evenement::class)->findAll(); 

        return $this->render('evenement/index.html.twig', array(
            'entities' => $entities,
            'newEntity' => new Evenement,
        ));
    }

    /**
     * @Route("/show/{id}", name="show", requirements={"id" = "\d+"})
     */
    public function show($id)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository(Evenement::class)->findOneById($id);

        return $this->render('evenement/show.html.twig', array(
            'entity' => $entity,
            'mediaWithPhotoIdent' => $entity->getMediaWithPhotoIdent(),
        ));
    }

    /**
     * @Route("/new", name="new")
     */
    public function new(Request $request, EventDispatcherInterface $eventDispatcher, TranslatorInterface $translator)
    {
        // Affiche un deny Access si l'utilisateur ne peut pas modifier
        // $this->denyAccessUnlessGranted('create', $evenement);

        $entity = new Evenement;
        $entity->setIdUserCreateur($this->getUser());
        $form = $this->createForm(EvenementType::class, $entity);
        $form->handleRequest($request); // Envoi les données de requêtes (POST) au formulaire

        if ($form->isSubmitted() && $form->isValid()) { // Si le form est envoyé et valide
            // Ajout du nouvel evenement dans la db
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity); // Prépare la requête
            $em->flush(); // Execute la requête

            // Crée un message de confirmation
            $this->addFlash('success', $translator->trans('evenement.new.success'));

            // Déclanchement de l'événement 'evenement.add'
            $event = new GenericEvent($entity);
            $eventDispatcher->dispatch('evenement.add', $event);

            return $this->redirectToRoute('evenement_index'); // Retour sur la liste des evenements
        }

        return $this->render('evenement/new.html.twig', array(
            'form' => $form->createView(), // Envoi le formulaire à la vue
        ));
    }

    /**
     * @Route("/edit/{id}", name="edit", requirements={"id" = "\d+"})
     */
    public function edit(Request $request, Evenement $entity, TranslatorInterface $translator)
    {
        // Affiche un deny Access si l'utilisateur ne peut pas modifier
        $this->denyAccessUnlessGranted('edit', $entity);
        // $this->isGranted('edit', $evenement);

        $form = $this->createForm(EvenementType::class, $entity);
        $form->handleRequest($request); // Envoi les données de requêtes (POST) au formulaire

        if ($form->isSubmitted() && $form->isValid()) { // Si le form est envoyé et valide
            // Ajout du nouvel evenement dans la db
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity); // Prépare la requête
            $em->flush(); // Execute la requête

            // Crée un message de confirmation
            $this->addFlash('success', $translator->trans('evenement.edit.success'));

            return $this->redirectToRoute('evenement_index'); // Retour sur la liste des evenements
        }

        return $this->render('evenement/edit.html.twig', array(
            'form' => $form->createView(), // Envoi le formulaire à la vue
            'entity' => $entity,
        ));
    }

    /**
     * @Route("/delete/{id}", name="delete", requirements={"id" = "\d+"})
     */
    public function delete(Request $request, Evenement $evenement): Response
    {
        // Affiche un deny Access si l'utilisateur ne peut pas modifier
        $this->denyAccessUnlessGranted('edit', $evenement);

        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($evenement);
            $em->flush();
        }

        return $this->redirectToRoute('evenement_index');
    }
}

templates/evenement/_delete_form.html.twig
{# C'est visible seulement si l'user connecté est l'usercreateur sont pareils #}
<button type="button" class="btn bg-secondary" data-toggle="modal" data-target="#deleteModal">
  Supprimer
</button>

<form method="post" action="{{ path('evenement_delete', {'id': entity.id }) }}">
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="deleteModalLabel">Supression d'un évènement</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Etes-vous sûr de vouloir supprimer cet évènement ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Annuler</button>
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ entity.id) }}">
        <button class="btn bg-secondary">Supprimer</button>
      </div>
    </div>
  </div>
</div>
</form>

templates/evenement/_form.html.twig
<div class="row">
    <div class="col-md-8">
        {{ form_row(form.image) }}
    </div>
    <div class="col-md-4 col-lg-2">
        {% if entity is defined and entity.image is not empty %}
            <img class="w-100" src="{{ asset('/uploads/img/' ~ entity.image.path) }}" alt="{{ entity.nom }}" />
            {{ form_row(form.deleteImage) }}
        {% endif %}
    </div>
</div>
{{ form_widget(form) }}

templates/evenement/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Modification de {{ entity.nom }} | P'tites Scènes{% endblock %}

{% block page_content %}
    <div class="evenement row justify-content-center">
        <div class="col-10 px-0 mt-3 pb-5">
            {{ form_start(form) }}
                {% embed 'decorator/_card.html.twig' %}
                    {% block header %}
                        <h1>Modification d'un évenement</h1>
                    {% endblock %}
        
                    {% block body %}
                        {{ include('evenement/_form.html.twig', {'button_label': 'Modifier'}) }}
                    {% endblock %}
        
                    {% block footer %}
                        <a class="btn btn-dark" href="{{ path('evenement_show', {'id': entity.id }) }}">Annuler</a>
                        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
                    {% endblock %}
                {% endembed %}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock page_content %}

templates/evenement/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Evenements | P'tites Scènes{% endblock %}

{% block page_content %}

<div class="evenement row justify-content-center">
    <div class="col-10 px-0 mt-3 pb-5">

        <div class="events row">

            {% for entity in entities %}
                <div class="allEvents col-sm-12 col-md-6 col-lg-4 col-xl-3 my-3">
                    {% if is_granted('edit', entity) %}
                    <div class="border-createur-evt vignette">
                    {% else %}
                    <div class="border-standard vignette">
                    {% endif %}
                        <a href="{{ path('evenement_show', {'id': entity.id}) }}">
                            <div class="event-image">
                                {% if entity.getMediaWithPhotoIdent() is not empty %}
                                    <img class="card-img" src="{{ asset('/uploads/img/' ~ entity.getMediaWithPhotoIdent().lien) }}" alt="{{ entity.getMediaWithPhotoIdent().titre }}">
                                {% elseif entity.image is not empty %}
                                    <img class="card-img" src="{{ asset('/uploads/img/' ~ entity.image.path) }}" alt="{{ entity.nom }}">
                                {% else %}
                                    <img class="card-img" src="{{ asset('/img/event_def.jpg') }}" alt="Card image cap">
                                {% endif %}
                            </div>
                            <div class="event-infos text-center">
                                <p class="lead text-primary">{{ entity.nom }}</p>
                                <p class="text-light"><small>{{ entity.type }} | {{ entity.styles ? entity.styles|join(', ') : '' }}</small></p>
                                <p class="text-secondary">{{ entity.date|date("d/m/Y") }} - {{ entity.heureDebut|date('H:i') }} | {{ entity.ville }}</p>
                            </div>
                        </a>

                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}

templates/evenement/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Créer un événement | P'tites Scènes{% endblock %}

{% block page_content %}
    <div class="evenement row justify-content-center">
        <div class="col-10 px-0 mt-3 pb-5">
            {{ form_start(form) }}
                {% embed 'decorator/_card.html.twig' %}
                    {% block header %}
                        <h1> {{ 'evenement.new.title'|trans }} </h1>
                    {% endblock header %}
        
                    {% block body %}
                        {{ include('evenement/_form.html.twig', {'button_label': 'Créer'}) }}
                    {% endblock body %}
        
                    {% block footer %}
                        <a class="btn btn-dark" href="{{ path('evenement_index') }}">Annuler</a>
                        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
                    {% endblock footer %}
                {% endembed %}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ entity.nom }} | P'tites Scènes{% endblock %}

{% block page_content %}

<div class="evenement row justify-content-center">
    <div class="col-10 px-0 mt-3 pb-5">
        <div class="card">
            <div class="card-body p-0">
                <div class="card-group">
                    <div class="card col-3 bg-secondary">
                        {% if mediaWithPhotoIdent is not empty %}
                            <img class="card-img-top" src="{{ asset('/uploads/img/' ~ mediaWithPhotoIdent.lien) }}" alt="{{ mediaWithPhotoIdent.titre }}">
                        {% elseif entity.image is not empty %}
                            <img class="card-img-top mt-3 mb-3" src="{{ asset('/uploads/img/' ~ entity.image.path) }}" alt="{{ entity.nom }}">
                        {% else %}
                            <img class="card-img-top mt-3 mb-3" src="{{ asset('/img/event_def.jpg') }}" alt="Card image cap">
                        {% endif %}
                    </div>
        
                    <div class="card col-4 text-dark bg-secondary text-center">
                        <div class="card-body">
                            <h2 class="card-title">{{ entity.nom }}</h2>
                            <h3 class="card-text mt-5">
                                {{ entity.type }} 
                                {{ entity.styles ? entity.styles|join(', ') : '' }}
                            </h3>
                            <h4 class="card-text mt-3">
                                {{ entity.date|date("d/m/Y") }} - 
                                {{ entity.heureDebut|date('H:i') }} à {{ entity.heureFin|date('H:i') }} - 
                                {{ entity.tarif }} €
                            </h4>
                            <ul class="list-group mt-5">
                                {% if entity.artistes is not empty or entity.formations is not empty %}
                                <li class="list-group-item bg-secondary">
                                    <h5>Participants :
                                        {% for artiste in entity.artistes %}
                                            {# <a href="#" class="card-link"> #}
                                                {% if artiste.nomArtiste is not empty %}
                                                    {{ artiste.nomArtiste }}
                                                {% else %}
                                                    {{ artiste.prenom }} {{ artiste.nom }}
                                                {% endif %}
                                            {# </a>     #}
                                        {% endfor %}
        
                                        {% for formation in entity.formations %}
                                            {# <a href="#" class="card-link">  #}
                                                {{ formation.nom }} 
                                            {# </a>     #}
                                        {% endfor %}
                                    </h5>
                                </li>
                                {% endif %}
                                <li class="list-group-item bg-secondary">
                                    <h5>Lieu : 
                                        {% if entity.lieu is not empty %}
                                            {# <a href="#" class="card-link">  #}
                                                {{ entity.lieu.nom }}
                                            {# </a>                          #}
                                        {% else %}
                                            {{ entity.adresse }} - 
                                            {{ entity.codepostal }} - 
                                            {{ entity.ville }}
                                        {% endif %}
                                    </h5>
                                </li>
                                <li class="list-group-item bg-secondary">
                                    <h5>Contact :
                                        {% if entity.userContact is not empty %}
                                            {# <a href="#" class="card-link"> #}
                                                {{ entity.userContact.prenom }} {{ entity.userContact.nom }}
                                            {# </a>     #}
                                        {% else %}
                                            {{ entity.numTelephone }}
                                        {% endif %}
                                    </h5>
                                </li>
                            </ul>
                        </div>
                    </div>
        
                    <div class="card col-5 text-dark bg-secondary">
                        <div class="card-body">
                            <h5> {{ entity.presentation }} </h5>
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-footer text-right bg-light">
                <div class="btn-group">
                    <a href="{{ path('evenement_index') }}" class="btn btn-primary">Retour</a>
                    {% if is_granted('edit', entity) %}
                            <a href="{{ path('evenement_edit', {'id': entity.id }) }}" class="btn btn-dark">Modifier</a>
                            {{ include('evenement/_delete_form.html.twig') }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}